version: "3.4"

services:
  networkprocessingwebapp:
      build: NetworkProcessingWebApp
      volumes:
          - ./:/networking_data_generation
      command: gunicorn NetworkProcessingWebApp.network_processing:create_app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
      ports:
          - 8080:8080
      depends_on:
          - postgres

  postgres:
      image: postgres:10
      volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=networks
      ports:
      - 5432:5432

volumes:
  dbdata:
